services:
  sumirabber-scheduler-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://localhost:5002/api"
    container_name: sumirabber-scheduler-web
    ports:
      - "3002:3000"
    restart: unless-stopped
